name: TEP CI-Workflow

on:
  #pull_request:
  #  branches: [ develop ]
  push:
    
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]



    services:
      sqlServer:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        env:
          ACCEPT_EULA: y
          SA_PASSWORD: 1StrongPwd!!
          MSSQL_PID: Express
        ports:
          - 1433:1433




    env:
      ConnectionStringTep: ${{ secrets.CONECTION_STRING }}
    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      
      run: dotnet test --no-restore --verbosity minimal
    #CODE COVERAGE TO DO NEXT
    #CODE COVERAGE TO A Artifact 
