name: TEP CI-Workflow

on:
  #pull_request:
  #  branches: [ develop ]
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlServer:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        env:
          ACCEPT_EULA: y
          SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MSSQL_PID: Express
        ports:
          - 1433:1433
    env:
      ConnectionStringTep: ${{ secrets.CONECTION_STRING }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Tests      
      run: dotnet test --no-restore --verbosity minimal
    #CODE COVERAGE TO DO NEXT
    #CODE COVERAGE TO A Artifact 